openapi: 3.1.0
info:
  title: Finance Agent API
  description: API para gestionar transacciones financieras (gastos e ingresos) con autenticación por API Key
  version: v1.0.0
servers:
  - url: https://your-app.railway.app
paths:
  /transactions:
    post:
      operationId: createTransaction
      summary: Registrar nueva transacción
      description: Crea un gasto o ingreso en el sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - amount
              properties:
                type:
                  type: string
                  enum: [gasto, ingreso]
                  description: Tipo de transacción
                amount:
                  type: number
                  minimum: 0
                  description: Monto de la transacción
                card:
                  type: string
                  description: Tarjeta utilizada (opcional)
                description:
                  type: string
                  description: Descripción de la transacción
                category:
                  type: string
                  description: Categoría (comida, transporte, salario, etc)
                date:
                  type: string
                  format: date-time
                  description: Fecha de la transacción (opcional, por defecto ahora)
      responses:
        '201':
          description: Transacción creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Transaction'
    get:
      operationId: getTransactions
      summary: Listar transacciones
      description: Obtiene lista de transacciones con filtros opcionales
      parameters:
        - name: type
          in: query
          description: Filtrar por tipo (gasto o ingreso)
          required: false
          schema:
            type: string
            enum: [gasto, ingreso]
        - name: category
          in: query
          description: Filtrar por categoría
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Límite de resultados (máximo 500)
          required: false
          schema:
            type: integer
            default: 500
            minimum: 1
            maximum: 500
      responses:
        '200':
          description: Lista de transacciones
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
  /transactions/{id}:
    delete:
      operationId: deleteTransaction
      summary: Eliminar transacción
      description: Elimina una transacción por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la transacción
          schema:
            type: string
      responses:
        '200':
          description: Transacción eliminada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Transaction'
  /summary:
    get:
      operationId: getSummary
      summary: Obtener resumen financiero
      description: Calcula totales de gastos, ingresos y balance
      responses:
        '200':
          description: Resumen financiero
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
components:
  schemas:
    Transaction:
      type: object
      properties:
        _id:
          type: string
          description: ID único de la transacción
        type:
          type: string
          enum: [gasto, ingreso]
          description: Tipo de transacción
        amount:
          type: number
          description: Monto de la transacción
        card:
          type: string
          description: Tarjeta utilizada
        description:
          type: string
          description: Descripción
        category:
          type: string
          description: Categoría
        date:
          type: string
          format: date-time
          description: Fecha de la transacción
    Summary:
      type: object
      properties:
        totalGastos:
          type: number
          description: Total de gastos
        totalIngresos:
          type: number
          description: Total de ingresos
        balance:
          type: number
          description: Balance (ingresos - gastos)
